//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StronaMuzy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.ReplayComments = new HashSet<ReplayComment>();
        }
    
        public int id { get; set; }
        public string Msg { get; set; }
        public System.DateTime Date { get; set; }
        public int id_Song { get; set; }
        public int id_User { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual Song Song { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReplayComment> ReplayComments { get; set; }
    }
}
